env:
  global:
    - secure: SkM5+JkgvqcGkBCKVNZXhXGLPzECUzUlGR/RmL0gXiNxC7OkieRVkZEWzginxKzs3d2GeDmmF5yP6bPdNoIlfO+ouqiG9h6VdrAdrAbxcc4L4NAhGe0Sn1l3+e8blZ4jvK9Y4ypUwgCI2q8YlvlTs+rG3GSREHBdUuBwCr8TV0Fj1p8+pfQNHTG1TU/ebLzlf0ls/2OtdjPecuh2DyObKTcEO1WMXJ4weTRBVPqkE9ws2YV0RmJF1MfnmHxRd2iuL7cPIv7aU28iHNG49b5SjjkELNkGaqqxj3GAlX1uayu8c3MHsRZ6yI94Z3jkvXgs2T2qm0z8/GvPH/16trZ+mBqr7sfn2tKM0tbJL2tuRa31okFdS4KxoKwWlSfInrD//XPx+GqsFJdoKkj7hU1ulW2GhhyklC8DIV9A7igBtYTUfcV0O2O+fkPhnFlY++7u3oj1Px6vtt71brdmiUeJ3zDrlnkfNU0ht4Vb20KTiHdfGB782sii/GfQDtpIjxuUBG+RTiFQhdnfNpg6WT5NprTfHIhKehYwv+nRi/VuxgE25JaMqs48SUi8DwPm+UaOGw84tap29S6hjGeWODx+CwwWPFhLRI+MErD6MCrYM9F0jyHjFMFJwAngdQOx5UjHxIbJJlG51eN3K903NuntOPJFnDUnixcFn1bV4Wt3hCc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO
    - GIT_BRANCH: master
sudo: required
dist: trusty

language: php
php:
  - '7.1'
  
matrix:
#  include:
#    - php: 5.6
#  allow_failures:
#    - php: 5.6
#    - php: hhvm
  fast_finish: true

cache:
  - apt

before_install:
  - export TZ=Africa/Johannesburg
  - sudo apt-get -y install expect
  - sudo apt-get -y install whois
  - sudo apt-get -y install dos2unix
  - sudo apt-get -y install realpath
  #- sudo apt-get -y install php7.0-cli

script:
  #- bash .dev-tools/deploy.sh
  - bash -x .dev-tools/interrogate-travis.sh
  #- bash -x .dev-tools/deploy-test.sh

notifications:
  email: false
