language: php

env:
  global:
    - secure: w7FDb+tofB5e+ej2GQDvOtlI75wADWuEsgYKCbiFnC4YKLGaN/NyNaAMuOdCPaLL6yWieHCTOQyG/zjVxZe8ST4R+2XQHv1x1PldbEHKnox+bAnrB9n3qZ0a8AOBtceI33gbrpL1wnZiVdcCh5HFlhvEOsiXhg+tc4BaIUZnA981dcf0EmIvWHWesmrgHVVh7x5Isgs5ecEpxyZZqn8FkHMgTnYe2s3IIlcIQhdvK2AhI33zz0fb1B9V/ll6UtAmbLKrYcN7waw/ZRzRDxuzJbCV6VCCFKzXo2DEs5NlEoa0P2bJAEj9dS5Q+1DGK5u1llbnycUBaS0phURb3gg8bcjX/9Ovlz/qnpw9EfimGxE7T6WjfI3sOQ9mFszgs/BigtZkay4ijGRNejrSiyC+/du/B0srto032HD8LTJBkbW5/OW9sr2JDmnOHJiceks4C8WYBVgvslLfnTD6tDgvJ88kjpk33Juq5ULm5ZcsJNQn+Dvn1btWQc1y9aRfktmyrTHoGTUXTx6c/YWXSdhuXVGCGgwxQ6PoOmhNeETuCKaA0dwoK1sACvgxJRDZCQpj7DneVGl7qqwr7LHQMrDMID+iXfr6ZMbFtC4HmK1PaDSxnPON/ecvEJLbUVRheo/70lYCYj2rlc7ytAUvMZ29Hzc353/GqF5FqxzX4kEubi8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO
    - GIT_BRANCH: master

sudo: required
dist: trusty

matrix:
  include:
    - php: 7.0
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

cache:
  - apt

before_install:
  - export TZ=Africa/Johannesburg

script:
  - bash .dev-tools/modify-files-and-commit.sh

before_deploy:
  - bash .dev-tools/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  skip_cleanup: true
  on:
    repo: mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false